cc:
  about: "PRODUCTION about message"
  welcome-message: "Welcome to PRODUCTION"

spring:
  datasource:
    url: "jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}"
    username: "${PGUSER}"
    password: "${PGPASSWORD}"
