spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "password"
    driver-class-name: "org.postgresql.Driver"
  sql:
    init:
      mode: "always"
  profiles:
    active:
      - production

logging:
  level:
    org:
      springframework:
        jdbc: "DEBUG"

cc:
  about: "This is a Calendar Content Application"
  welcome-message: "Welcome to Content Calendar"

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: "always"

